import type { RoleCode } from "@prisma/client";

import { PERMISSIONS, type PermissionCode } from "./permissions";

export const ROLE_PERMISSION_MATRIX_VERSION =
  "2026-07-23-location-notes-contacts-v1";

export type PlatformRoleCode = "platform_owner";
export type TenantRoleCode = RoleCode;
export type AppRoleCode = PlatformRoleCode | TenantRoleCode;

const COMPANY_ADMIN_PERMISSIONS = [
  PERMISSIONS.TENANT_SETTINGS_READ,
  PERMISSIONS.TENANT_SETTINGS_MANAGE,
  PERMISSIONS.USERS_READ,
  PERMISSIONS.USERS_INVITE,
  PERMISSIONS.USERS_MANAGE,
  PERMISSIONS.ROLES_ASSIGN,
  PERMISSIONS.LOCATIONS_READ,
  PERMISSIONS.LOCATIONS_MANAGE,
  PERMISSIONS.LOCATIONS_ASSIGN,
  PERMISSIONS.LOCATION_INSIGHTS_READ,
  PERMISSIONS.LOCATION_INSIGHTS_MANAGE,
  PERMISSIONS.LOCATION_NOTES_MANAGE,
  PERMISSIONS.CONTACTS_READ,
  PERMISSIONS.CONTACTS_MANAGE,
  PERMISSIONS.PRODUCTS_READ,
  PERMISSIONS.PRODUCTS_MANAGE,
  PERMISSIONS.IMPORTS_READ,
  PERMISSIONS.IMPORTS_UPLOAD,
  PERMISSIONS.IMPORTS_CONFIRM,
  PERMISSIONS.AUDIT_READ,
  // Company admins run onboarding, so they need the pilot readiness/review
  // screen (/admin/pilot) and its GET /pilot-review/summary data.
  PERMISSIONS.PILOT_REVIEW_READ,
] as const satisfies readonly PermissionCode[];

export const ROLE_PERMISSION_MATRIX = {
  platform_owner: [
    PERMISSIONS.PLATFORM_TENANTS_READ,
    PERMISSIONS.PLATFORM_TENANTS_MANAGE,
    PERMISSIONS.PLATFORM_OPERATIONS_READ,
  ],

  // The tenant superadmin holds everything a company_admin holds plus
  // admin-management permissions — it is a strict superset, not a separate
  // role a user also needs company_admin for. See
  // docs/plans/tenant-superadmin-plan-prompt.md.
  tenant_superadmin: [
    ...COMPANY_ADMIN_PERMISSIONS,
    PERMISSIONS.ADMINS_INVITE,
    PERMISSIONS.ADMINS_MANAGE,
  ],

  company_admin: COMPANY_ADMIN_PERMISSIONS,

  team_manager: [
    PERMISSIONS.LOCATIONS_READ,
    PERMISSIONS.LOCATION_INSIGHTS_READ,
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.ROUTES_READ,
    PERMISSIONS.ROUTES_MANAGE_TEAM,
    PERMISSIONS.VISITS_READ_TEAM,
    PERMISSIONS.REPORTS_READ_TEAM,
    PERMISSIONS.TASKS_READ_TEAM,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE_TEAM,
    PERMISSIONS.DASHBOARD_MANAGER_READ,
    PERMISSIONS.PILOT_REVIEW_READ,
  ],

  field_representative: [
    PERMISSIONS.LOCATIONS_READ,
    PERMISSIONS.LOCATION_INSIGHTS_READ,
    PERMISSIONS.LOCATION_INSIGHTS_MANAGE_OWN,
    PERMISSIONS.LOCATION_NOTES_MANAGE_OWN,
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.CONTACTS_MANAGE_OWN,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.ROUTES_READ,
    PERMISSIONS.ROUTES_MANAGE_OWN,
    PERMISSIONS.VISITS_READ_OWN,
    PERMISSIONS.VISITS_CREATE,
    PERMISSIONS.VISITS_UPDATE_OWN,
    PERMISSIONS.VISITS_CANCEL_OWN,
    PERMISSIONS.REPORTS_READ_OWN,
    PERMISSIONS.REPORTS_CONFIRM_OWN,
    PERMISSIONS.TASKS_READ_OWN,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE_OWN,
    PERMISSIONS.AI_USE_REPORTING,
  ],
} as const satisfies Record<AppRoleCode, readonly PermissionCode[]>;
