import type { RoleCode } from "@prisma/client";

import { PERMISSIONS, type PermissionCode } from "./permissions";

export const ROLE_PERMISSION_MATRIX_VERSION = "2026-06-29-mvp-team-v1";

export type PlatformRoleCode = "platform_owner";
export type TenantRoleCode = RoleCode;
export type AppRoleCode = PlatformRoleCode | TenantRoleCode;

export const ROLE_PERMISSION_MATRIX = {
  platform_owner: [
    PERMISSIONS.PLATFORM_TENANTS_READ,
    PERMISSIONS.PLATFORM_TENANTS_MANAGE,
    PERMISSIONS.PLATFORM_OPERATIONS_READ,
  ],

  company_admin: [
    PERMISSIONS.TENANT_SETTINGS_READ,
    PERMISSIONS.TENANT_SETTINGS_MANAGE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_INVITE,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ROLES_ASSIGN,
    PERMISSIONS.LOCATIONS_READ,
    PERMISSIONS.LOCATIONS_MANAGE,
    PERMISSIONS.LOCATIONS_ASSIGN,
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.CONTACTS_MANAGE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.IMPORTS_READ,
    PERMISSIONS.IMPORTS_UPLOAD,
    PERMISSIONS.IMPORTS_CONFIRM,
    PERMISSIONS.AUDIT_READ,
  ],

  team_manager: [
    PERMISSIONS.LOCATIONS_READ,
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.ROUTES_READ,
    PERMISSIONS.ROUTES_MANAGE_TEAM,
    PERMISSIONS.VISITS_READ_TEAM,
    PERMISSIONS.REPORTS_READ_TEAM,
    PERMISSIONS.TASKS_READ_TEAM,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE_TEAM,
    PERMISSIONS.DASHBOARD_MANAGER_READ,
    PERMISSIONS.PILOT_REVIEW_READ,
  ],

  field_representative: [
    PERMISSIONS.LOCATIONS_READ,
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.ROUTES_READ,
    PERMISSIONS.ROUTES_MANAGE_OWN,
    PERMISSIONS.VISITS_READ_OWN,
    PERMISSIONS.VISITS_CREATE,
    PERMISSIONS.VISITS_UPDATE_OWN,
    PERMISSIONS.VISITS_CANCEL_OWN,
    PERMISSIONS.REPORTS_READ_OWN,
    PERMISSIONS.REPORTS_CONFIRM_OWN,
    PERMISSIONS.TASKS_READ_OWN,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE_OWN,
    PERMISSIONS.AI_USE_REPORTING,
  ],
} as const satisfies Record<AppRoleCode, readonly PermissionCode[]>;
